C:\Java9LanguageFeatures>java ^
--module-path dist\jdojo.prime.jar;
    dist\jdojo.prime.client.jar;
    dist\jdojo.prime.faster.jar;
    dist\jdojo.prime.probable.jar ^
--show-module-resolution ^
--module jdojo.prime.client/com.jdojo.prime.client.Main

root jdojo.prime.client ... 
jdojo.prime.client requires jdojo.prime ... 
jdojo.prime binds jdojo.prime.probable ... 
jdojo.prime binds jdojo.prime.faster... 
... 
